---
# 
# Install Couchbase cluster from a single command
#

- name: Couchbase Installation
  hosts: all
  user: root
   
  tasks:

  - name: download Couchbase package
    get_url: url=http://packages.couchbase.com/releases/4.0.0/couchbase-server-community_4.0.0-ubuntu14.04_amd64.deb dest=~
 
  - name: Install dependencies
    apt: pkg=libssl0.9.8 state=present

  - name: Install Couchbase .deb file on all machines
    shell: dpkg -i ~/couchbase-server-community_4.0.0-ubuntu14.04_amd64.deb
     
- name: Initialize the cluster and add the nodes to the cluster
  hosts: couchbase-main
  user: root 

  tasks:
  - name: Configure main node
    shell: /opt/couchbase/bin/couchbase-cli cluster-edit -c 127.0.0.1:8091  --cluster-username={{admin_user}} --cluster-password={{admin_password}} --cluster-port=8091 --cluster-ramsize={{cluster_ram_quota}} --services=data,index,query -u Administrator -p Inmar2016

  - name: Create shell script for configuring main node
    action: template src=couchbase-add-node.j2 dest=/tmp/addnodes.sh mode=750
  
  - name: Launch config script
    action: shell /tmp/addnodes.sh
  
  - name: Rebalance the cluster
    shell: /opt/couchbase/bin/couchbase-cli rebalance -c 127.0.0.1:8091 -u {{admin_user}} -p {{admin_password}}      
  
  - name: Get bucket name
    uri: url="http://localhost:8091/pools/default/buckets" return_content=yes
    register: json_response


  - debug: msg="{{(json_response.content|from_json)[1]['name']}}"
    when:  (json_response.content|from_json)[1]  is defined

  - name: create bucket ${bucket_name} with ${num_replicas} replicas
    shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=${bucket_name} --bucket-type=couchbase --bucket-port=11222 --bucket-ramsize=100  --bucket-replica=1 --enable-flush=1 -u ${admin_user} -p ${admin_password} --wait
    when: (json_response.content|from_json)[1]['name'] != "blah_bucket"
    register: results
    ignore_errors: True
